apiVersion: v1
kind: Service
metadata:
  name: food-nexus-service
  labels:
    app: food
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: food

